name: meeting_transcriber
description: 온디바이스 AI 기반 음성인식 회의록 받아쓰기 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # 상태 관리
  provider: ^6.1.1

  # 음성 인식 (온디바이스 AI - Whisper.cpp)
  whisper_ggml: ^1.7.0
  record: ^5.0.4

  # 권한 관리
  permission_handler: ^11.3.0

  # 구글 드라이브 연동
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # 로컬 저장소
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3

  # 유틸리티
  intl: ^0.19.0
  uuid: ^4.3.3

  # 파일 처리
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
